logging:
  level:
    sql: debug
    org.hibernate.SQL: debug

spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      platform: h2
  jpa:
    hibernate:
      ddl-auto: create-drop

h2:
  tcp:
    enabled: true