spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: update
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8080}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true
  health:
    readinessState:
      enabled: true
    livenessState:
      enabled: true