apiVersion: v1
kind: PersistentVolume
metadata:
  name: user-pv
  namespace: k8s-program
spec:
  storageClassName: manual
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/mydir

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-pvc
  namespace: k8s-program
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G