apiVersion: v1
kind: Secret
metadata:
  name: post-db-credentials
  namespace: k8s-program
type: Opaque
data:
# base64 encoded word 'postgres'
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=

---

apiVersion: v1
kind: Secret
metadata:
  name: user-db-credentials
  namespace: k8s-program
type: Opaque
data:
  # base64 encoded word 'postgres'
  DB_USERNAME: cG9zdGdyZXM=
  DB_PASSWORD: cG9zdGdyZXM=