apiVersion: v1
kind: Service
metadata:
  name: post-service-app
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: post-service-pod
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: user-service-app
  namespace: k8s-program
spec:
  type: NodePort
  selector:
    app: user-service-pod
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: post-service-db
spec:
  type: ClusterIP
  ports:
    - name: "db-port"
      protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    app: post-service-postgres

---

apiVersion: v1
kind: Service
metadata:
  namespace: k8s-program
  name: user-service-db
spec:
  type: ClusterIP
  ports:
    - name: "db-port"
      protocol: "TCP"
      port: 5432
      targetPort: 5432
  selector:
    app: user-service-postgres
