spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.h2.H2ConsoleAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
  show_sql: true